site_name: BD - Bases de Datos
theme: 
  name: material
  logo: assets/logocaminas.png
  features:
    #  - navigation.tabs
    #  - navigation.sections
      - navigation.top
      - navigation.path
    #- navigation.expand
      - navigation.indexes
      - toc.integrate
      - search.highlight
      - content.code.annotation
      - content.code.copy  
extra_css:
  - stylesheets/extra.css
nav:
  - Tema 1-Introducció:
    - Objectius: BD-T01_Introduccio/objectius.md
    - 1. Fitxers tradicionals: BD-T01_Introduccio/1_fitxers_tradicionals.md
    - 2. Concepte de Base de Dades: BD-T01_Introduccio/2_concepte_de_base_de_dades.md
    - 3. Característiques desitjables d'un SGBD: BD-T01_Introduccio/3_caracterstiques_desitjables_dun_sgbd.md
    - 4. Models de dades: BD-T01_Introduccio/4_models_de_dades.md
    - 5. Arquitectura a 3 nivells: BD-T01_Introduccio/5_arquitectura_a_3_nivells.md
    - 6. Llenguatges del SGBD: BD-T01_Introduccio/6_llenguatges_del_sgbd.md
    - 7. Classificacions dels SGBD: BD-T01_Introduccio/7_classificacions_dels_sgbd.md
    - Autoavaluació: BD-T01_Introduccio/autoavaluaci.md
  

markdown_extensions:
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - footnotes


   